name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "19 5 * * 3"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt 

      - name: Analyse the Project
        working-directory: ./faultybot
        run: |
          pylint --rcfile="./.pylintrc" `ls -R|grep .py$|xargs`

      - name: Clean
        run: |
          git clean -fX